version: "3.9"
services:
  domain:
    build:
      context: domain
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - "./domain:/app"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changethis
    depends_on:
      - neo4j
    restart: on-failure

  patient:
    build:
      context: patient
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./patient:/app"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changethis
    depends_on:
      - neo4j
    restart: on-failure
  
  neo4j:
    image: neo4j:4.3.2-community    
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=changethis
    restart: on-failure
    volumes:
      - "./neo4j/data:/data"
